import type { ColumnKind } from "@/lib/csv";

export type TemplateColumn = {
  name: string;
  type: ColumnKind;
  pk?: boolean;
  note?: string;
};

export type TemplateTable = {
  key: string;
  display_name: string;
  description: string;
  columns: TemplateColumn[];
  /** Which columns act as foreign keys to another template table. */
  fks?: { column: string; references: { table: string; column: string } }[];
  /** Which of the template's four steps this table belongs to. */
  step: 1 | 2 | 3 | 4;
};

export type ProjectTemplate = {
  key: string;
  name: string;
  tagline: string;
  description: string;
  /** Labels for steps 1-4, in order. Domain vocabulary lives here, not in the UI. */
  steps?: [string, string, string, string];
  tables: TemplateTable[];
  example_queries?: ExampleQuery[];
};

export type ExampleQuery = {
  name: string;
  description: string;
  sql: string;
};

/** Used when a template declares no step labels (e.g. AI-generated ones). */
export const DEFAULT_STEP_LABELS: [string, string, string, string] = [
  "Core tables",
  "Linked tables",
  "Measurements",
  "Reference",
];

export function stepLabels(template: ProjectTemplate): [string, string, string, string] {
  return template.steps ?? DEFAULT_STEP_LABELS;
}

/**
 * Templates are data, not code: every `templates/*.json` file becomes a project
 * type. Adding a discipline (concrete, geotech, hydrology, …) is a new JSON
 * file — no changes to this module.
 */
const modules = import.meta.glob<{ default: ProjectTemplate }>("../../templates/*.json", {
  eager: true,
});

export const TEMPLATES: ProjectTemplate[] = Object.entries(modules)
  .map(([path, mod]) => {
    const t = mod.default;
    if (!t?.key || !Array.isArray(t.tables)) {
      throw new Error(`Invalid project template at ${path}: "key" and "tables" are required`);
    }
    return t;
  })
  .sort((a, b) => a.name.localeCompare(b.name));

export function getTemplate(key: string | null | undefined): ProjectTemplate | null {
  if (!key) return null;
  return TEMPLATES.find((t) => t.key === key) ?? null;
}

export type TemplateMeta = {
  /** Map from template table key -> dataset.id (uuid) once uploaded. */
  bindings?: Record<string, string>;
  /** Confirmed FK column mappings: template table key -> { fkColumn: parentColumn } */
  fk_mappings?: Record<string, Record<string, string>>;
  /** Runtime template generated by the AI folder import (renders in ErdDiagram). */
  ai_template?: ProjectTemplate;
};
